name: Build brotli
on:
  workflow_dispatch:
    inputs:
      version:
        description: brotli tag to build
        required: true
      php:
        description: PHP version to build for
        required: true
defaults:
  run:
    shell: cmd
jobs:
  build:
    strategy:
      matrix:
          arch: [x64, x86]
    runs-on: windows-2022
    steps:
      - name: Checkout winlib-builder
        uses: actions/checkout@v4
        with:
          path: winlib-builder
      - name: Checkout brotli
        uses: actions/checkout@v4
        with:
          path: brotli
          repository: google/brotli
          ref: ${{github.event.inputs.version}}
      - name: Compute virtual inputs
        id: virtuals
        run: powershell winlib-builder/scripts/compute-virtuals -version ${{github.event.inputs.php}} -arch ${{matrix.arch}}
      - name: Configure brotli
        run: md build && cd build && cmake -G "Visual Studio 17 2022" -A ${{steps.virtuals.outputs.msarch}} -T ${{steps.virtuals.outputs.msts}} -DCMAKE_SYSTEM_VERSION=${{steps.virtuals.outputs.winsdk}} ..\brotli
      - name: Build brotli
        run: cd build && cmake --build . --config RelWithDebInfo
      - name: Install brotli
        run: |
          cd build
          cmake --install . --config RelWithDebInfo --prefix ..\install
          xcopy RelWithDebInfo\brotli*.pdb ..\install\bin\*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.inputs.version}}-${{steps.virtuals.outputs.vs}}-${{matrix.arch}}
          path: install
