name: Build glib
on:
  workflow_dispatch:
    inputs:
      version:
        description: glib tag to build
        required: true
      php:
        description: PHP version to build for
        required: true
      stability:
        description: the series stability
        required: false
        default: 'staging'
defaults:
  run:
    shell: cmd
jobs:
  build:
    strategy:
      matrix:
          arch: [x64, x86]
    runs-on: windows-2022
    steps:
      - name: Checkout winlib-builder
        uses: actions/checkout@v4
        with:
          path: winlib-builder
      - name: Checkout glib
        uses: actions/checkout@v4
        with:
          path: glib
          repository: winlibs/glib
          ref: ${{github.event.inputs.version}}
      - name: Compute virtual inputs
        id: virtuals
        run: powershell winlib-builder/scripts/compute-virtuals -version ${{github.event.inputs.php}} -arch ${{matrix.arch}}
      - name: Fetch dependencies
        run: powershell winlib-builder/scripts/fetch-deps -lib glib -version ${{github.event.inputs.php}} -vs ${{steps.virtuals.outputs.vs}} -arch ${{matrix.arch}} -stability ${{github.event.inputs.stability}}
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
      - name: Build glib
        run: cd glib && msbuild /p:Configuration=Release_BundledPCRE;Platform=${{steps.virtuals.outputs.msarch}};PlatformToolset=${{steps.virtuals.outputs.msts}};WindowsTargetPlatformVersion=${{steps.virtuals.outputs.winsdk}};PythonPath=C:\hostedtoolcache\windows\Python\3.7.9\x64 win32\vs${{steps.virtuals.outputs.vsnum}}\glib.sln
      - name: Install glib
        run: xcopy /e vs${{steps.virtuals.outputs.vsnum}}\${{steps.virtuals.outputs.msarch}} install\*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.inputs.version}}-${{steps.virtuals.outputs.vs}}-${{matrix.arch}}
          path: install
