name: Build libbzip2
run-name: "Build ${{ inputs.version }} for PHP ${{ inputs.php }}"
on:
  workflow_dispatch:
    inputs:
      version:
        description: libbzip2 tag to build
        required: true
      php:
        description: PHP version to build for
        required: true
defaults:
  run:
    shell: cmd
jobs:
  build:
    strategy:
      matrix:
          arch: [x64, x86]
    runs-on: ${{ (inputs.php == '8.6' || inputs.php == 'master') && 'windows-2025-vs2026' || 'windows-2022' }}
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout winlib-builder
        uses: actions/checkout@v5
        with:
          path: winlib-builder
      - name: Checkout libbzip2
        uses: actions/checkout@v5
        with:
          path: libbzip2
          repository: winlibs/libbzip2
          ref: ${{github.event.inputs.version}}
      - name: Compute virtual inputs
        id: virtuals
        run: powershell winlib-builder/scripts/compute-virtuals -version ${{github.event.inputs.php}} -arch ${{matrix.arch}}
      - name: Setup MSVC development environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: ${{steps.virtuals.outputs.toolset}}
      - name: Build libbzip2 release
        run: cd libbzip2 && nmake /f makefile.msc
      - name: Install libbzip2 release
        run: |
          cd libbzip2
          xcopy bzlib.h ..\build\include\*
          xcopy libbz2_a.* ..\build\lib\*
      - name: Clean libbzip2
        run: cd libbzip2 && nmake /f makefile.msc clean
      - name: Build libbzip2 debug
        run: cd libbzip2 && nmake /f makefile_debug.msc
      - name: Install libbzip2 debug
        run: |
          cd libbzip2
          xcopy libbz2_a_debug.* ..\build\lib\*
      - name: Copy license files
        run: xcopy libbzip2\LICENSE build\share\licenses\libbzip2\*
      - name: Generate SBOMs
        shell: pwsh
        run: >
          .\winlib-builder\scripts\generate-sbom.ps1
          -Library libbzip2
          -Version '${{ github.event.inputs.version }}'
          -InstallRoot 'build'
          -Vs '${{ steps.virtuals.outputs.vs }}'
          -Arch '${{ matrix.arch }}'
          -PhpVersion '${{ github.event.inputs.php }}'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.inputs.version}}-${{steps.virtuals.outputs.vs}}-${{matrix.arch}}
          path: build
