name: Build libssh2
on:
  workflow_dispatch:
    inputs:
      version:
        description: libssh2 tag to build
        required: true
      php:
        description: PHP version to build for
        required: true
      stability:
        description: the series stability
        required: false
        default: 'staging'
defaults:
  run:
    shell: cmd
jobs:
  build:
    strategy:
      matrix:
          arch: [x64, x86]
    runs-on: windows-2022
    steps:
      - name: Checkout winlib-builder
        uses: actions/checkout@v4
        with:
          path: winlib-builder
      - name: Checkout libssh2
        uses: actions/checkout@v4
        with:
          path: libssh2
          repository: winlibs/libssh2
          ref: ${{github.event.inputs.version}}
      - name: Compute virtual inputs
        id: virtuals
        run: powershell winlib-builder/scripts/compute-virtuals -version ${{github.event.inputs.php}} -arch ${{matrix.arch}}
      - name: Fetch dependencies
        run: powershell winlib-builder/scripts/fetch-deps -lib libssh2 -version ${{github.event.inputs.php}} -vs ${{steps.virtuals.outputs.vs}} -arch ${{matrix.arch}} -stability ${{github.event.inputs.stability}}
      - name: Configure libssh2
        run: cd libssh2 && cmake -G "Visual Studio 16 2019" -A ${{steps.virtuals.outputs.msarch}} -T ${{steps.virtuals.outputs.msts}} -DCRYPTO_BACKEND=OpenSSL -DOPENSSL_ROOT_DIR:PATH=${{github.workspace}}/deps -DENABLE_ZLIB_COMPRESSION=ON -DZLIB_INCLUDE_DIR:PATH=${{github.workspace}}/deps/include -DZLIB_LIBRARY:FILEPATH=${{github.workspace}}/deps/lib/zlib_a.lib -DBUILD_SHARED_LIBS=ON .
      - name: Build libssh2
        run: cd libssh2 && cmake --build . --config RelWithDebInfo
      - name: Install libssh2
        run: |
          cd libssh2
          cmake --install . --config RelWithDebInfo --prefix ..\build
          copy src\RelWithDebInfo\libssh2.pdb ..\build\bin
          move ..\build\include ..\build\include1
          mkdir ..\build\include
          move ..\build\include1 ..\build\include\libssh2
          del /s /q ..\build\lib\pkgconfig\*
          del /s /q ..\build\share\*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.inputs.version}}-${{steps.virtuals.outputs.vs}}-${{matrix.arch}}
          path: build
