name: Build libzstd
on:
  workflow_dispatch:
    inputs:
      version:
        description: libzstd tag to build
        required: true
      php:
        description: PHP version to build for
        required: true
      stability:
        description: the series stability
        required: false
        default: 'staging'
defaults:
  run:
    shell: cmd
jobs:
  build:
    strategy:
      matrix:
          arch: [x64, x86]
    runs-on: windows-2022
    steps:
      - name: Checkout winlib-builder
        uses: actions/checkout@v4
        with:
          path: winlib-builder
      - name: Checkout libzstd
        uses: actions/checkout@v4
        with:
          path: libzstd
          repository: facebook/zstd
          ref: ${{github.event.inputs.version}}
      - name: Compute virtual inputs
        id: virtuals
        run: powershell winlib-builder/scripts/compute-virtuals -version ${{github.event.inputs.php}} -arch ${{matrix.arch}}
      - name: Patch libzstd
        run: cd libzstd && git apply --ignore-whitespace ..\winlib-builder\patches\libzstd.patch
      - name: Configure libzstd
        run: cd libzstd\build\cmake && cmake -G "Visual Studio 16 2019" -A ${{steps.virtuals.outputs.msarch}} -T ${{steps.virtuals.outputs.msts}} .
      - name: Build libzstd
        run: cd libzstd\build\cmake && cmake --build . --config RelWithDebInfo
      - name: Install libzstd
        run: |
          cd libzstd\build\cmake
          cmake --install . --config RelWithDebInfo --prefix ..\..\..\install
          cd ..\..
          copy COPYING ..\install
          copy LICENSE ..\install
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libzstd-${{github.event.inputs.version}}-${{steps.virtuals.outputs.vs}}-${{matrix.arch}}
          path: install
