name: Build lmdb
on:
  workflow_dispatch:
    inputs:
      version:
        description: lmdb tag to build
        required: true
      php:
        description: PHP version to build for
        required: true
defaults:
  run:
    shell: cmd
jobs:
  build:
    strategy:
      matrix:
          arch: [x64, x86]
    runs-on: windows-2022
    steps:
      - name: Checkout winlib-builder
        uses: actions/checkout@v4
        with:
          path: winlib-builder
      - name: Checkout lmdb
        uses: actions/checkout@v4
        with:
          path: lmdb
          repository: winlibs/lmdb
          ref: ${{github.event.inputs.version}}
      - name: Compute virtual inputs
        id: virtuals
        run: powershell winlib-builder/scripts/compute-virtuals -version ${{github.event.inputs.php}} -arch ${{matrix.arch}}
      - name: Setup MSVC development environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: ${{steps.virtuals.outputs.toolset}}
      - name: Build lmdb
        run: cd lmdb\libraries\liblmdb && nmake /f Makefile.vc
      - name: Install lmdb
        run: |
          cd lmdb\libraries\liblmdb
          xcopy *.exe ..\..\..\build\bin\*
          xcopy lmdb.h ..\..\..\build\include\*
          xcopy liblmdb_a.* ..\..\..\build\lib\*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.inputs.version}}-${{steps.virtuals.outputs.vs}}-${{matrix.arch}}
          path: build
