name: Build pslib
on:
  workflow_dispatch:
    inputs:
      version:
        description: pslib tag to build
        required: true
      php:
        description: PHP version to build for
        required: true
      stability:
        description: the series stability
        required: false
        default: 'staging'
defaults:
  run:
    shell: cmd
jobs:
  build:
    strategy:
      matrix:
          arch: [x64, x86]
    runs-on: windows-2022
    steps:
      - name: Checkout winlib-builder
        uses: actions/checkout@v4
        with:
          path: winlib-builder
      - name: Checkout pslib
        uses: actions/checkout@v4
        with:
          path: pslib
          repository: winlibs/pslib
          ref: ${{github.event.inputs.version}}
      - name: Compute virtual inputs
        id: virtuals
        run: powershell winlib-builder/scripts/compute-virtuals -version ${{github.event.inputs.php}} -arch ${{matrix.arch}}
      - name: Configure pslib
        run: cd pslib && cmake -G "Visual Studio 16 2019" -A ${{steps.virtuals.outputs.msarch}} -T ${{steps.virtuals.outputs.msts}} .
      - name: Build pslib
        run: cd pslib && cmake --build . --config RelWithDebInfo
      - name: Install pslib
        run: |
          cd pslib
          xcopy COPYING ..\install\*
          xcopy RelWithDebInfo\pslib.dll ..\install\bin\*
          xcopy RelWithDebInfo\pslib.pdb ..\install\bin\*
          xcopy include\libps\*.h ..\install\include\libps\*
          xcopy RelWithDebInfo\pslib.lib ..\install\lib\*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.inputs.version}}-${{steps.virtuals.outputs.vs}}-${{matrix.arch}}
          path: install
