name: Build pthreads
on:
  workflow_dispatch:
    inputs:
      version:
        description: pthreads tag to build
        required: true
      php:
        description: PHP version to build for
        required: true
      stability:
        description: the series stability
        required: false
        default: 'staging'
defaults:
  run:
    shell: cmd
jobs:
  build:
    strategy:
      matrix:
          arch: [x64, x86]
    runs-on: windows-2022
    steps:
      - name: Checkout winlib-builder
        uses: actions/checkout@v4
        with:
          path: winlib-builder
      - name: Checkout pthreads
        uses: actions/checkout@v4
        with:
          path: pthreads
          repository: winlibs/pthreads
          ref: ${{github.event.inputs.version}}
      - name: Compute virtual inputs
        id: virtuals
        run: powershell winlib-builder/scripts/compute-virtuals -version ${{github.event.inputs.php}} -arch ${{matrix.arch}}
      - name: Setup MSVC development environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: ${{steps.virtuals.outputs.toolset}}
      - name: Build pthreads
        run: cd pthreads && nmake clean VC
      - name: Install pthreads
        run: |
          cd pthreads
          xcopy pthreadVC?.dll ..\build\bin\*
          xcopy pthreadVC?.pdb ..\build\bin\*
          xcopy _ptw32.h ..\build\include\*
          xcopy pthread.h ..\build\include\*
          xcopy sched.h ..\build\include\*
          xcopy pthreadVC?.lib ..\build\lib\*
          if exist COPYING xcopy COPYING ..\build\*
          if exist LICENSE xcopy LICENSE ..\build\*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.inputs.version}}-${{steps.virtuals.outputs.vs}}-${{matrix.arch}}
          path: build
