name: Build zlib
on:
  workflow_dispatch:
    inputs:
      version:
        description: zlib tag to build
        required: true
      php:
        description: PHP version to build for
        required: true
defaults:
  run:
    shell: cmd
jobs:
  build:
    strategy:
      matrix:
          arch: [x64, x86]
    runs-on: windows-2022
    steps:
      - name: Checkout winlib-builder
        uses: actions/checkout@v4
        with:
          path: winlib-builder
      - name: Checkout zlib
        uses: actions/checkout@v4
        with:
          path: zlib
          repository: winlibs/zlib
          ref: ${{github.event.inputs.version}}
      - name: Compute virtual inputs
        id: virtuals
        run: powershell winlib-builder/scripts/compute-virtuals -version ${{github.event.inputs.php}} -arch ${{matrix.arch}}
      - name: Setup MSVC development environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: ${{steps.virtuals.outputs.toolset}}
      - name: Build zlib
        run: cd zlib && nmake -f win32/Makefile.msc zlib_a.lib
      - name: Install zlib
        run: |
          cd zlib
          xcopy zconf.h ..\build\include\*
          xcopy zlib.h ..\build\include\*
          xcopy zutil.h ..\build\include\*
          xcopy zlib_a.lib ..\build\lib\*
          xcopy zlib_a.pdb ..\build\lib\*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.event.inputs.version}}-${{steps.virtuals.outputs.vs}}-${{matrix.arch}}
          path: build
